### ISSUE TITLE
Please add the three releases to grml-debootstrap releasename

### ISSUE THREAD

**Issue by suntong** [grml/grml-debootstrap#149] opened 2020-01-23 16:02 UTC
Debian always has at least three releases in active maintenance: stable, testing and unstable.  
-- https://www.debian.org/releases/

Please add them to the `grml-debootstrap` `--releasename` valid inputs. IMHO, those are better than the moving target of lenny, squeeze, wheezy, jessie, stretch, buster, and bullseye, which always make my head spin and have to look them up *each time* I need to make a choice. 

Thanks

**Comment by mika** [comment] 2020-01-23 16:47
I don't think generic release codenames are something to be encouraged, that's why we even have an explicit check for this in grml-debootstrap, to _not_ use that. If you deploy Debian `stable` you get (dist)upgrades whenever a new Debian release gets published, without explicitly asking for it, and not once _you_ decide to do so. While this might be fine for you personally, I don't think it's expected behavior nor something we should encourage users to use as such.

grml-debootstrap already defaults to the current stable Debian release, so there actually shouldn't be much to remember for you:

```
-r, --release <name>   Release of new Debian system (default: buster).
```

Also when using `stable` (instead of a specific codename) it's hard to enable specific workarounds/fixes in grml-debootstrap itself, since we typically don't know what `stable` refers to at the time of execution (and then we'd have even more guessing etc in our codebase which I prefer to keep as small and stupid as possible).

So unless you've a very compelling reason why we should reconsider this I'll close this bugreport.
If there's anything broken or unclear WRT release name handling though, please let us know. :)

**Closed by mika** 2020-01-23 16:47 UTC

**Comment by suntong** [comment] 2020-01-23 22:48
Then can I ask at least for "testing"?

**Comment by mika** [comment] 2020-01-24 07:33
The same problem for `testing` applies here as well, we don't know what `testing` is referring to when executing grml-debootstrap. :-/

I'm not sure it warrants efforts on our side (which also includes any possible bug reports around it if installing `testing` doesn't work), given that you can install current Debian `testing` via `grml-debootstrap -r bullseye ...` already, and if you want to stay on the testing track then adjust sources.list accordingly.

Any other opinions, @evgeni @jkirk @zeha @formorer?

**Comment by evgeni** [comment] 2020-01-24 08:41
I prefer names (or actually numbers, but Debian does not have that option for us) for my installs, as this naming is stable (haha).

On the other hand users are free to do whatever they want to their installs ;)
So kinda undecided here.

**Comment by suntong** [comment] 2020-01-24 19:45
OK, now I fully understand your concerns. 
Fair enough, that makes sense. So I'm good now. 
Case close. :)
