### ISSUE TITLE
iface lo inet dhcp

### ISSUE THREAD

**Issue by jkirk** [grml/grml-debootstrap#132] opened 2019-04-25 12:29 UTC
*Quick and dirty report, sorry!*

In my latest installation I noticed the following:

```
allow-hotplug lo
iface lo inet dhcp
```

**Comment by mika** [comment] 2019-05-31 13:43
This is actually caused by ISOs around and including the Grml 2018.12 release, which provides a `allow-hotplug lo` entry within its /etc/network/interfaces.

Solved via https://github.com/grml/live-boot-grml/commit/ad4ec759ed2d8e76de01c9351cfaa6f8062def0c and also can be avoided by using grml-debootstrap's `--defaultinterfaces` option.

Closing hereby.

**Closed by mika** 2019-05-31 13:43 UTC
