### ISSUE TITLE
EFI variables are not supported on this system.

### ISSUE THREAD

**Issue by bathtime** [grml/grml-debootstrap#189] opened 2021-11-29 19:04 UTC
This could easily be due to the way I'm setting up my partitions. I've tried several ways, and I can only get grml-debootstrap to boot with grub on my old laptop. This variation attempts to install with grub and efi.

Command issued:
`grml-debootstrap --grub /dev/sdb --efi /dev/sdb2 --target /dev/sdb1`

fdisk /dev/sdb
```
Disk /dev/sdb: 14.65 GiB, 15728640000 bytes, 30720000 sectors
Disk model:                 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: A9B63170-2C17-444A-82DE-C3484D68EA1B

Device        Start      End  Sectors  Size Type
/dev/sdb1      2048 30310366 30308319 14.5G Linux filesystem
/dev/sdb2  30310400 30719966   409567  200M EFI System
```

Main error:
```
Setting up efibootmgr (17-1) ...
Mounting /dev/sdb2 on /boot/efi
Invoking efibootmgr
EFI variables are not supported on this system.
 -> Failed (rc=1)
 * Removing chroot-script again
 * Unmounting bind-mount /run/udev
 * Unmount /mnt/debootstrap.2193
umount: /mnt/debootstrap.2193: target is busy.
 -> Failed (rc=32)
 * Removing /var/cache/grml-debootstrap/variables_sdb1
 * Removing /var/cache/grml-debootstrap/stages_sdb1
Stopping OpenBSD Secure Shell server: sshd.

 * Unmounting /mnt/debootstrap.2193
Removing stages directory /var/cache/grml-debootstrap/stages_sdb1: done
 * Removing directory /mnt/debootstrap.2193
 * Notice: remove /var/cache/grml-debootstrap/stages_sdb1/umount_chroot to reexecute the stage
```

Full log:
[grml.log](https://github.com/grml/grml-debootstrap/files/7620511/grml.log)

Thanks

**Comment by mika** [comment] 2021-11-29 19:11
You hit a rather unfortunate bug that was caused by a pretty-close-to-the-release change in Debian kernels, by dropping support for `CONFIG_EFI_VARS` in >=5.10. I assume you're running such a kernel on your system. This issue is known to be fixed with newer versions of grml-debootstrap, so for the time being grab grml-debootstrap either from Debian testing or unstable, or use the one provided in the Grml repository (https://deb.grml.org/pool/main/g/grml-debootstrap/grml-debootstrap_0.99_all.deb).

(It would be nice to get this bug fixed in Debian stable/bullseye, I didn't manage to motivate myself to look into this so far…)

**Comment by bathtime** [comment] 2021-12-01 01:58
Thank you for the quick response!

Updating solved the issue indicated, but I noticed that I got an error concerning _grml-etc-core_ not being found when I just installed the individual pack, as opposed to installing from Debian unstable (Currently running Debian 11—bullseye).

For those not experienced at installing from unstable, to save you some time, here's what I did:

Add the repo:
`echo 'deb http://deb.debian.org/debian unstable main contrib non-free' >> /etc/apt/sources.list`

Then paste this content into the the file:

/etc/apt/preferences:
```
Package: *
Pin: release a=bullseye
Pin-Priority: 500

Package: *
Pin: release a=unstable
Pin-Priority: 100
```

Then update, remove the old package, and install the new one:
```
apt update
apt remove grml-debootstrap
apt install -t unstable grml-debootstrap
```

...

All this aside, there are no errors, but my oldish laptop and new desktop computer—both legacy and UEFI compatible—have yet to boot the USB. I'll eventually get this solved, but for now I just used Debian's mini.iso in VirtualBox to install Debian onto my USB. The trick is to remove the host system and add the USB (it's a PITA, to be sure). That worked fine for both computers. Problem is that you aren't able to make the nice install script and have everything ready on boot as you can with grml-debootstrap.

So, I'm not giving up on grml-debootstrap. It's very likely just a small thing on my side that I'm not doing correctly. And I'm really liking this quick response to my issues!

**Closed** 2021-12-01 02:44 UTC

**Comment by mika** [comment] 2021-12-01 06:18
@bathtime thanks for your feedback, also that you provided instructions for others how you solved it! :+1: 
Let us know if you have any further issues!
