### ISSUE TITLE
Missing NTP client *systemd-timesyncd*

### ISSUE THREAD

**Issue by paulmenzel** [grml/grml-debootstrap#197] opened 2022-08-26 17:04 UTC
Since *systemd* 247.9-2, *systemd-timesyncd* is only a recommended instead of depended on:

>   * Demote systemd-timesyncd from Depends to Recommends.
>     This avoids a dependency cycle between systemd and systemd-timesyncd and
>     thus makes dist upgrades more predictable and robust.
>     It also allows minimal, systemd based containers where no NTP client is
>     strictly necessary.
>     To ensure that systemd-timesyncd is installed in a default installation
>     created by d-i, bump its priority to standard. (Closes: #986651, #993947)

I added *systemd-timesyncd* to `packages`, but should grml-debootstrap install an NTP client by default?

**Comment by mika** [comment] 2022-08-26 17:29
It's a `Recommends` only in Debian/bullseye and `Debian/unstable`:

```
% apt-cache show systemd/bullseye | grep -e Version -e systemd-timesyncd
Version: 247.3-7
Recommends: dbus, systemd-timesyncd | time-daemon
% apt-cache show systemd/unstable | grep -e Version -e systemd-timesyncd
Version: 251.4-1
Recommends: default-dbus-system-bus | dbus-system-bus, systemd-timesyncd | time-daemon
```

AFAICT it made it as a strict dependency (as in `Depends`) only into the systemd backport for buster (see 
https://packages.debian.org/buster-backports/systemd), but also not into buster (see https://packages.debian.org/buster/systemd).
So from my PoV it never was a hard dependency in any actual Debian/release, or am I missing something?

**Comment by paulmenzel** [comment] 2022-08-26 17:49
No, I missed, that it’s different between the suites. As grml-debootstrap allows to install different suites like sid/unstable, I wonder if it can be supported for all suites.

**Comment by mika** [comment] 2022-11-11 09:37
AFAICT this is not a bug, so I'd suggest we close this, unless we need to change/fix something, please report then :)

**Closed by mika** 2022-11-11 09:37 UTC
